name: BetterTPA
author: RoboMWM
version: ${project.version}
main: me.robomwm.BetterTPA.BetterTPA
commands:
    tpblock:
      usage: /tpblock <player> - Blocks a player from sending you teleport requests.
      aliases: [tpablock, tpban, tpaban, tpdeny, tpadeny]
    tpallow:
      usage: /tpallow <player> - Allows a player to teleport to you.
      aliases: [tpyes, tpayes, tpaccept]
    tpa:
      usage: /tpa <player> - Teleports u 2 dat player. Sends a teleport proposal if it is ur 1st time.
      aliases: [tpask]
    tpremove:
      usage: /tpremove <player> - Removes a player from ur /tpallow list.
    tplist:
      usage: Shows who you allowed or blocked
      aliases: [tpalist]
permissions:
    bettertpa.*:
        description: Why
        children:
            bettertpa.nowarmup.override: true
            bettertpa.receiveteleports: true
    bettertpa.nowarmup:
        description: If both teleporter and teleportee have this permission, warmup will be bypassed.
        default: false
    bettertpa.nowarmup.override:
        description: Bypass warmup in all situations
        default: op
    bettertpa.receiveteleports:
        description: Allows players to /tpa to this person. Useful if you want to limit access to some worlds.
        default: true
